### ISSUE TITLE
Participant checkin backend

### ISSUE THREAD

**Issue by opxz7148** [OmegaOoh/ku-tangtee#133]
**Describe the solution you'd like**
API for let activities participant able to check-in.

**Additional context**
POST activities/check-in/<activity_id>/ + check-in code (Inside query param or in a payload)

**Comment by OmegaOoh** [comment]
What is the difference between this and #129

**Comment by opxz7148** [comment]
> What is the difference between this and [#129](https://github.com/OmegaOoh/ku-tangtee/issues/129) except different name

#129 is just big task that haven't got seperate yet. It's should be close I'm just forget about it.
