### ISSUE TITLE
Cannot properly input the detail with multiple lines

### ISSUE THREAD

**Issue by TeerapatTrepopsakulsin** [OmegaOoh/ku-tangtee#192]
**Describe the bug**
If I try to separate activity details into multiple lines, they'll still be shown in paragraph format (as shown below).

**To Reproduce**
1. Create an activity with multiple lines of detail
2. Go to the activity detail page

**Expected behavior**
Show activity detail in separate line according to the input

**Screenshots**
Input:
```Sunset Beach Yoga Class

Description: Join us for a rejuvenating sunset yoga class on Miami Beach.

Location: Miami Beach, near the South Beach Pavilion. Address: 10 Ocean Drive, Miami Beach, FL

Instructor: Name: Ashley Morgan. Qualifications: Certified Yoga Instructor with 10 years of experience in Hatha and Vinyasa yoga

What to Bring: Yoga mat or towel, water bottle, comfortable clothing, optional: sunscreen, sunglasses

Amenities: Restrooms, changing facilities, free parking, refreshments provided

Price: $20 per person. Special Offer: Bring a friend and get 10% off for both

Contact Information: Email: info@sunsetyoga.com. Phone: (555) 123-4567

Additional Information: Please arrive 15 minutes early to set up your spot and settle in. The class will start promptly at 6:00 PM. In case of bad weather, the class will be rescheduled, and participants will be notified via chat.
```
_This is AI generated, so don't care too much about the context_

Output:
![Image](https://github.com/user-attachments/assets/ea062efe-59b4-4a1f-a02e-00eac3496126)

**Desktop:**
Window 11, Microsoft Edge

**Comment by OmegaOoh** [comment]
It seems to be fixed already in markdown formatter
