### ISSUE TITLE
I create an Activity by set max people = 1 and I can't use chat to talk to myself : (

### ISSUE THREAD

**Issue by Ichi1234** [OmegaOoh/ku-tangtee#259]
**Describe the bug**
I create an Activity by set max people = 1 and I can't use chat to talk to myself. It said to me that the chat is not connect please refresh. Therefore, I refresh it but it still said the same. DAMN IT! I want to talk to myself.

**To Reproduce**
1. Go to menu bar
2. Click on Host Activity
3. Scroll down to  Max people
4. Set max people = 1
5. Click on the activity
6. Scroll down to chat
7. click on chat
8. Try to talk to your self
9. See an error

**Expected behavior**

I WANT TO TALK TO MY SELF WHO HOST THE ACTIVITY THAT ONLY ME EXIST

**Screenshots**
![image](https://github.com/user-attachments/assets/7c49fe78-673b-4ec2-8e11-2efe1dc98cbb)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser  Chrome
 - Version 10

**Additional context**
I want to sleep

**Comment by Thanawas-Sirilertsathit** [comment]
Well chat is not available for now. We already stated that issue before you shot us.

**Comment by Thanawas-Sirilertsathit** [comment]
It should be able to talk but the websocket for every chat channel contains error for now. We are going to fix that asap.

**Comment by Thanawas-Sirilertsathit** [comment]
![image](https://github.com/user-attachments/assets/1330ad7f-a646-40eb-8e10-3955e30d4d48)

**Comment by OmegaOoh** [comment]
This issue is duplicated with #256 .
