### ISSUE TITLE
Images do not display after a certain period

### ISSUE THREAD

**Issue by KhunakornP** [OmegaOoh/ku-tangtee#263]
**Describe the bug**
The site images are gone after some time. Affects Images that have been posted for some time but not recent images

**To Reproduce**
1. Create an activity and add images
2. Wait for around 8 hours
3. Check the activity again

**Expected behavior**
The activity still displays the image.

**Screenshots**
Activity created on 23/11/2024 at around 22.00
![no_img](https://github.com/user-attachments/assets/d749f6d6-0c84-4107-8e40-919ae47171b8)

Activity created on 24/11/2024 at around 12.55
![img](https://github.com/user-attachments/assets/4edd1da6-b8fc-4849-aae1-9c2c45cb7c65)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  Version 131.0.6778.86

**Comment by OmegaOoh** [comment]
We're investigating the bug, but the Image disappeared after redeploying the backed server.

**Comment by opxz7148** [comment]
After investigation I've found out that the problem cause by wrong persistent disk mount path that make media that got upload doesn't properly add into persistent disk and disappear every time service are redeploy. I've fix by change disk mount path and it's should work right now. But unfortunately image that got uploaded before cannot be recover sorry about that. If the problem doesn't resolve feel free to open this issue again.
