### ISSUE TITLE
You can create the exact same activity many times.

### ISSUE THREAD

**Issue by KhunakornP** [OmegaOoh/ku-tangtee#264]
**Describe the bug**
You can create the exact same activity many times even down to the activity title.
You can also spam the create button to create the same activity

**To Reproduce**
1. Create an activity
2. Fill out the activity details
3. Either: 
    - Do it again
    - Spam the button

**Expected behavior**
An error message or only 1 activity is created.

**Screenshots**

![uh oh](https://github.com/user-attachments/assets/ae4219e5-3f40-48e6-b46c-15c364f12445)

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 131.0.6778.86 (Official Build) (64-bit)

**Additional context**
I may have intentionally spammed the site with a parody of the You are an Idiot virus I am sorry for the disruption.

**Comment by opxz7148** [comment]
Already prevent this by add several constraint to Django models
