### ISSUE TITLE
Filter shows activities outside selected date range and day

### ISSUE THREAD

**Issue by PHIMNADA024** [OmegaOoh/ku-tangtee#265]
**Describe the bug**
When filtering activities by date (from 1/1/2025 to 31/1/2025) and selecting "Friday," the results include activities outside the specified date range and day. The filter does not behave as expected, causing inaccurate results.

**To Reproduce**
1. Navigate to the Home page.
2. Click on the filter option.
3. Set the date range to 1/1/2025 - 31/1/2025 and select "Friday."
4. Observe that activities outside this range and day are still displayed.

**Expected behavior**
The filter should only show activities that fall within the specified date range and selected day.

**Screenshots**
![image](https://github.com/user-attachments/assets/45eaf118-a879-4ef1-ad07-26eab289ab01)

**Desktop (please complete the following information):**
 - OS: Window11
 - Browser: Chrome
 - Version: 23

**Comment by opxz7148** [comment]
This cause by conflict timezone already fixed.
