### ISSUE TITLE
Error when inputting invalid user information when sign up

### ISSUE THREAD

**Issue by knilios** [OmegaOoh/ku-tangtee#268]
**Describe the bug**
I was instantly logged out after I created a new account and entered a bunch of spaces in the input. And every time I re-login with my account, the same thing happens, except now my profile picture is displayed.

**To Reproduce**
1. Go to the home page.
2. Click on ```Login```
3. Select your KU account
4. Enter the following
 - Nickname: "                           "
 - Pronoun: "                           "
 - Bio: "                           "
 - KU Generation: 83
 - Faculty: "                           "
 - Major: "                           "
5. Click 'Submit'

**Expected behavior**
The app should tell me that my input is invalid.

**Screenshots**
![image](https://github.com/user-attachments/assets/4a73ee08-4e36-4ec4-9749-14a3ddc36ba8)
![image](https://github.com/user-attachments/assets/b196d839-6493-43ca-85ad-73108ee68a0c)
![image](https://github.com/user-attachments/assets/cb0b98c2-41a0-4aa0-9642-6a91136e45af)
![image](https://github.com/user-attachments/assets/f7273d07-aee6-46bc-bc29-a85db2000293)

**Desktop :**
 - OS: Windows
 - Browser: Edge
 - Version 131.0.2903.63

**Additional context**
This is not the first time I logged in. However, I think that the result is the same as the first time I created the account (Except for the account profile picture at the upper right on the account creation page).

**Comment by OmegaOoh** [comment]
The issue should be fixed in #267.
