### ISSUE TITLE
You can see chats for activities that you aren't apart of

### ISSUE THREAD

**Issue by KhunakornP** [OmegaOoh/ku-tangtee#270]
**Describe the bug**
You can you the REST API to spy on other activities chat when you haven't joined.

**To Reproduce**
1. Go to [REST API for chat](https://ku-tangtee-hhls.onrender.com/chat/)
2. Find an activity you didn't join with [REST API for activities](https://ku-tangtee-hhls.onrender.com/activities/)
3. Go to [REST API for chat](https://ku-tangtee-hhls.onrender.com/chat/) and add `<activity_id>/` to the path

**Expected behavior**
You shouldn't be able to call the API for chats that you are not authorized.

**Screenshots**
![chat leak](https://github.com/user-attachments/assets/486a729c-8ea5-47ee-9de7-b4c2187d3303)

**Desktop**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 131.0.6778.86 (Official Build) (64-bit)

**Comment by OmegaOoh** [comment]
Thanks for testing it, The issue should be fixed in #267 by add the permissions class to the Django views class
