### ISSUE TITLE
I can't use search function if I write more than 2500 words.

### ISSUE THREAD

**Issue by Pong50887** [OmegaOoh/ku-tangtee#273]
**Describe the bug**
The Search function doesn't work if the input has 2500+ words
PolDance with Loong PolDance with Loong PolDance with Loong PolDance with Loong
PolDance with Loong PolDance with Loong PolDance with Loong PolDance with Loong
PolDance with Loong PolDance with Loong PolDance with Loong PolDance with Loong
PolDance with Loong PolDance with Loong PolDance with Loong PolDance with Loong
PolDance with Loong PolDance with Loong PolDance with Loong PolDance with Loong 
PolDance with Loong PolDance with Loong PolDance with Loong PolDance with Loong
PolDance with Loong PolDance with Loong PolDance with Loong PolDance with Loong
PolDance with Loong PolDance with Loong PolDance with Loong PolDance with Loong
more lines omitted...

**To Reproduce**
1. Go to the default page
2. Click on activity input
3. input text 2500+ words
4. Click on the 'Search' button
5. See nothing filter, error 502 shows when inspecting

**Expected behavior**
The input should have a character limit.

**Screenshots**
![image](https://github.com/user-attachments/assets/7f7d9fb8-0cef-48ad-bebc-6757364e2ca6)

**Desktop (please complete the following information):**
 - OS: window 11
 - Browser Chrome
 - Version 23

**Comment by Thanawas-Sirilertsathit** [comment]
The description of activity is capped at 1024 letters. Activity title is capped at 200 letters.
In this case, it is enhancement more than bug because you just want to cap the letter limit in search bar. Generally use case of search bar is not for putting 2000 words in there to find stuffs.

**Comment by opxz7148** [comment]
We already limit search bar to only 250. Thank for suggestion.
