### ISSUE TITLE
Inconsistency branch naming.

### ISSUE THREAD

**Issue by Jwizzed** [OmegaOoh/ku-tangtee#91]
I suggest you stick with one format either "-" or "_".

<img width="317" alt="image" src="https://github.com/user-attachments/assets/ff202d0d-a346-4dbb-91e8-9ca7f379361a">

**Comment by opxz7148** [comment]
We already agreed to use this-format for all of branch. I've fix old branch name already only rest_framework_conversion branch that I've change yet since it's cause some difficulty if change name on working branch. After we've done with it, we're going to change it to correct format.

**Comment by opxz7148** [comment]
Already change all branch name to same format.
